---
- hosts: "{{hostlist}}"
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh

  tasks:
    - name: Copy join command to worker nodes.
      become: yes
      become_method: sudo
      copy:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 0777

    - name: Join the Worker nodes with the master.
      become: yes
      become_method: sudo
      command: sh /tmp/kubernetes_join_command
      register: joined_or_not

    - debug:
        msg: "{{ joined_or_not.stdout }}"
...
