---
- hosts: "{{hostlist}}"
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: yes
  connection: ssh

  tasks:
    - name: replace line
      lineinfile:
        path: /var/lib/kubelet/config.yaml
        regexp: "^(.*)cgroupDriver(.*)$"
        line: "cgroupDriver: systemd"
        backrefs: yes
    - name: Reboot all the kubernetes nodes.
      reboot:
        post_reboot_delay: 10
        reboot_timeout: 40
        connect_timeout: 60
        test_command: uptime
...
